CalcGridLayout:
<CustButton@Button>:
    color: 0,1,1,1
    background_color:(0.11,0.11,0.11,0.8)
    font_size: 20
 
<CalcGridLayout>:
    canvas.before:
        Color:
            rgba: (0, 0, 0,1)
        Rectangle:
            pos: self.pos
            size: self.size
    rows:6
    BoxLayout:
        TextInput:
            id: input
            font_size: 32
            multiline: False
            background_color:(0,0,0,1)
            foreground_color: (0,1,1,0.8)
            
    BoxLayout:
        CustButton:
            text: "7"
            on_press: root.on_click(7)
        CustButton:
            text: "8"
            on_press: root.on_click(8)
        CustButton:
            text: "9"
            on_press: root.on_click(9)
        CustButton:
            text:"÷"
            on_press: root.on_click("/")
    BoxLayout:
        CustButton:
            text: "4"
            on_press: root.on_click(4)
        CustButton:
            text: "5"
            on_press: root.on_click(5)
        CustButton:
            text: "6"
            on_press: root.on_click(6)
        CustButton:
            text:"x"
            on_press: root.on_click("*")
    BoxLayout:
        CustButton:
            text: "1"
            on_press: root.on_click(1)
        CustButton:
            text: "2"
            on_press: root.on_click(2)
        CustButton:
            text: "3"
            on_press: root.on_click(3)
        CustButton:
            text:"-"
            on_press: root.on_click("-")
    BoxLayout:
        CustButton:
            text: "AC"
            color: 0.11,0.11,0.11,0.8
            background_color:(0,1,1,0.8)
            on_press: root.on_clear()
        CustButton:
            text: "0"
            on_press: root.on_click(0)
        CustButton:
            text: "."
            on_press: root.on_click(".")
        CustButton:
            text:"+"
            on_press: root.on_click("+")
    BoxLayout:
        CustButton:
            text: "="
            on_press: root.evaluate()
